# This is a basic workflow to help you get started with Actions
name: Publish To Pub.Dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: ["master", "main"]
    paths-ignore:
      - '**/README.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publishing:
    name: Publish Plugin
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Dart Package
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{secrets.OAUTH_ACCESS_TOKEN}}
          refreshToken: ${{secrets.OAUTH_REFRESH_TOKEN}}
